language: node_js

node_js:
  - '12.16.1'

install:
  - yarn

script:
  - yarn run lint
  - yarn run typecheck
  - yarn test
  - yarn run build

cache:
  directories:
    - node_modules

after_success: sizereport --config
