language: node_js

node_js:
  - '12.16.1'

install:
  - npm install

script:
  - npm run lint
  - npm run typecheck
  - npm test
  - npm run build

cache:
  directories:
    - node_modules

after_success: sizereport --config
